"use client";

import { useEffect, useState } from "react";
import useSWR from "swr";
import { fetcher } from "lib/utils";
import { CreatorProfile } from "app-types/creator";
import { ChooseUsernameModal } from "@/components/choose-username-modal";
import { ChooseNameModal } from "@/components/choose-name-modal";

interface CreatorProfileCheckProps {
  userId?: string;
  userName?: string;
}

/**
 * This component manages the onboarding flow for new users:
 * 1. First asks for their personal name (user.name) - for greetings & AI
 * 2. Then asks for their unique @username - for public profile
 *
 * Both modals are mandatory and cannot be dismissed.
 */
export function CreatorProfileCheck({
  userId,
  userName,
}: CreatorProfileCheckProps) {
  const [showNameModal, setShowNameModal] = useState(false);
  const [showUsernameModal, setShowUsernameModal] = useState(false);
  const [isClient, setIsClient] = useState(false);

  // Only fetch if we have a userId
  const { data, isLoading, mutate } = useSWR<{
    hasProfile: boolean;
    profile: CreatorProfile | null;
  }>(userId ? "/api/creator-profile" : null, fetcher, {
    revalidateOnFocus: false,
    revalidateOnReconnect: false,
  });

  // Check if we're on the client
  useEffect(() => {
    setIsClient(true);
  }, []);

  useEffect(() => {
    if (!isClient || isLoading || !userId) return;

    // Check localStorage for completed onboarding steps
    const nameOnboardingKey = `onboarding_name_${userId}`;
    const nameCompleted = localStorage.getItem(nameOnboardingKey) === "true";

    // Check if name looks auto-generated (pattern: Word + Word + Number)
    const isAutoGeneratedName =
      userName && /^[A-Z][a-z]+[A-Z][a-z]+\d+$/.test(userName);

    // Step 1: If name is auto-generated and not completed, show name modal
    if (isAutoGeneratedName && !nameCompleted) {
      setShowNameModal(true);
      return;
    }

    // Step 2: If user doesn't have a creator profile, show username modal
    if (data && !data.hasProfile) {
      setShowUsernameModal(true);
    }
  }, [data, isLoading, userId, userName, isClient]);

  const handleNameSuccess = (_newName: string) => {
    // Mark name onboarding as complete in localStorage
    if (userId) {
      localStorage.setItem(`onboarding_name_${userId}`, "true");
    }
    setShowNameModal(false);

    // Force page reload to refresh the session with new name
    window.location.reload();
  };

  const handleUsernameSuccess = () => {
    setShowUsernameModal(false);
    mutate(); // Refresh the profile data
  };

  if (!userId) return null;

  return (
    <>
      <ChooseNameModal open={showNameModal} onSuccess={handleNameSuccess} />
      <ChooseUsernameModal
        open={showUsernameModal}
        onSuccess={handleUsernameSuccess}
      />
    </>
  );
}
